---
# handlers file for my_phpmyadmin
- name: restart firewall
  service:
    name: firewalld
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart mysql
  service:
    name: mysqld
    state: restarted
